# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: MattL07/ModOfRedemption

media_folder: "blog/media"
public_folder: "/blog/media"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm" }
      - { label: "Author", name: "author", widget: "string" }
#     - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", 
        name: "body",
        widget: "markdown", 
        #buttons: ["heading-two", "heading-three", "heading-four", "bold", "italic", "link", "quote", "code-block", "bulleted-list", "numbered-list"]
        }